ores:
  emerald:
    toggle: true #avaliable
    max: 20 #maximum y level
    min: 2 #minumum y level
    amount: 10 #maximum ore structure size
  diamond:
    toggle: true
    max: 20
    min: 2
    amount: 10
  gold:
    toggle: true
    max: 35
    min: 2
    amount: 10
  iron:
    toggle: true
    max: 60
    min: 2
    amount: 10
  coal:
    toggle: true
    max: 80
    min: 2
    amount: 10
  lapis:
    toggle: true
    max: 30
    min: 2
    amount: 10